### ISSUE TITLE
Spotify closed the local API?

### ISSUE THREAD

**Issue by dunklesToast** [f-mer/spotify-local-control#1]
Hey!

it looks like Spotify disabled the local API. I cannot find a Port where the API is running and the Tool is throwing errors.
The Web Player now uses Spotify Connect to access and control the local Player

**Comment by f-mer** [comment]
Hey 👋 Thanks for the issue. Haven't used this one in a long time. Yep, seems like Spotify moved on to using ~~their official api~~ spclient.wg.spotify.com. For anyone who tries to use functionality previously provided by this packages should take a look at https://developer.spotify.com.

~~I'm going to archive this repository and deprecate the packages as it provides not value anymore.~~
Maybe I will take a stab at reversing the new api.

Thanks a lot for looking into this :)
